accelerate launch examples/wanvideo/model_training/train.py \
  --dataset_base_path /mnt/bucket/dawy/video_generation/two_stage_dataset \
  --dataset_metadata_path /mnt/bucket/dawy/video_generation/two_stage_dataset/metadata_vanilla_full_train.csv \
  --data_file_keys "video,vace_video,vace_reference_image,vace_video_mask,loss_mask_video" \
  --height 480 \
  --width 832 \
  --dataset_repeat 2 \
  --model_id_with_origin_paths "Wan-AI/Wan2.1-VACE-1.3B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.1-VACE-1.3B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.1-VACE-1.3B:Wan2.1_VAE.pth" \
  --learning_rate 3e-4 \
  --batch_size 5 \
  --gradient_accumulation_steps 4 \
  --num_epochs 25 \
  --remove_prefix_in_ckpt "pipe.vace." \
  --output_path "./models/train/Wan2.1-VACE-1.3B_lora_latent_mask_loss" \
  --lora_base_model "vace" \
  --lora_target_modules "q,k,v,o,ffn.0,ffn.2" \
  --lora_rank 64 \
  --extra_inputs "video,vace_video,vace_reference_image,vace_video_mask,loss_mask_video" \
  --use_gradient_checkpointing_offload \
  --val_dataset_base_path /mnt/bucket/dawy/video_generation/two_stage_dataset \
  --val_dataset_metadata_path /mnt/bucket/dawy/video_generation/two_stage_dataset/metadata_vanilla_full_eval.csv \
  --val_data_file_keys "video,vace_video,vace_reference_image,vace_video_mask,loss_mask_video" \
  --val_batch_size 2 \
  --eval_every_n_epochs 1 \
  --eval_max_batches 50 \
  --loss_mask_weight 2.0 \
  --loss_mask_weight_end 0.5 \
  --loss_mask_hold_ratio 0.25 \
  --loss_mask_decay cosine \
  --loss_mask_skip_first_frame \
  --base_loss_weight_start 1 \
  --base_loss_weight_peak 2.0 \
  --base_loss_weight_end 1.5 \
  --base_loss_warmup_ratio 0.2 \
  --base_loss_hold_ratio 0.2 \
  --base_loss_decay cosine
  --loss_mask_skip_first_frame \
  --aug_enable \
  --aug_hflip_prob 0.5 \
  --aug_color_jitter_prob 0.3 \
  --aug_color_jitter_strength 0.2 \
  --aug_fog_prob 0.1 \
  --aug_rain_prob 0.1 \
  --aug_snow_prob 0.05 \
  --aug_sunflare_prob 0.05
